version: '3.8'

services:
  backend:
    build: ./course-up-backend
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - courseup-network

  frontend:
    build: ./course-up-frontend
    ports:
      - "3000:80"
    networks:
      - courseup-network

networks:
  courseup-network:
    driver: bridge
